### ISSUE TITLE
Prediction from MD runs

### ISSUE THREAD

**Issue by ricardojdgferreira** [Minys233/Dynafomer#1]
Hi,

very interesting work here!
Do you have any tutorial on how to perform evaluation directly from the MD run, or can you give me the basic commands?
I already saw that a 'rmsd.csv' file is needed, the trajectory as .dcd and PBD files.

**Comment by Minys233** [comment]
Thanks to your attention, the prediction from the MD trajectory can now be alternatively disassembled into predictions of each frame.  For example you can preprocess your trajectory and save the structures of each frame in the corresponding PDB and SDF format and run our model using the method described in the Custom Input section of the README.

Eg.

Trajectory(PSF/DCD)  -->  Structures (PDB/SDF) --> Prediction (CSV) --> Analysis
